const COURTS_BY_CITY = {
  // ── ANDHRA PRADESH ──
  'vijayawada': [
    'Principal District & Sessions Court, Krishna (Vijayawada)',
    'I Addl. District & Sessions Court, Vijayawada',
    'II Addl. District & Sessions Court, Vijayawada',
    'Family Court, Vijayawada',
    'Labour Court, Vijayawada',
    'Consumer Disputes Redressal Commission, Krishna',
    'Motor Accidents Claims Tribunal, Vijayawada',
    'Chief Judicial Magistrate Court, Vijayawada',
    'I Addl. Chief Judicial Magistrate Court, Vijayawada',
    'Permanent Lok Adalat, Vijayawada',
  ],
  'guntur': [
    'Principal District & Sessions Court, Guntur',
    'I Addl. District & Sessions Court, Guntur',
    'II Addl. District & Sessions Court, Guntur',
    'Family Court, Guntur',
    'Labour Court, Guntur',
    'Consumer Disputes Redressal Commission, Guntur',
    'Motor Accidents Claims Tribunal, Guntur',
    'Chief Judicial Magistrate Court, Guntur',
  ],
  'visakhapatnam': [
    'Principal District & Sessions Court, Visakhapatnam',
    'I Addl. District & Sessions Court, Visakhapatnam',
    'II Addl. District & Sessions Court, Visakhapatnam',
    'Family Court, Visakhapatnam',
    'Labour Court, Visakhapatnam',
    'Consumer Disputes Redressal Commission, Visakhapatnam',
    'Motor Accidents Claims Tribunal, Visakhapatnam',
    'Chief Judicial Magistrate Court, Visakhapatnam',
  ],
  'vizag': [
    'Principal District & Sessions Court, Visakhapatnam',
    'Family Court, Visakhapatnam',
    'Labour Court, Visakhapatnam',
    'Consumer Disputes Redressal Commission, Visakhapatnam',
    'MACT, Visakhapatnam',
  ],
  'tirupati': [
    'Principal District & Sessions Court, Chittoor (Tirupati)',
    'I Addl. District & Sessions Court, Tirupati',
    'Family Court, Tirupati',
    'Consumer Disputes Redressal Commission, Chittoor',
    'Labour Court, Tirupati',
    'MACT, Tirupati',
    'Chief Judicial Magistrate Court, Tirupati',
  ],
  'kurnool': [
    'Principal District & Sessions Court, Kurnool',
    'I Addl. District & Sessions Court, Kurnool',
    'Family Court, Kurnool',
    'Consumer Disputes Redressal Commission, Kurnool',
    'Labour Court, Kurnool',
    'MACT, Kurnool',
    'Chief Judicial Magistrate Court, Kurnool',
  ],
  'nellore': [
    'Principal District & Sessions Court, SPSR Nellore',
    'I Addl. District & Sessions Court, Nellore',
    'Family Court, Nellore',
    'Consumer Disputes Redressal Commission, Nellore',
    'Labour Court, Nellore',
    'MACT, Nellore',
    'Chief Judicial Magistrate Court, Nellore',
  ],
  'kadapa': [
    'Principal District & Sessions Court, YSR Kadapa',
    'Family Court, Kadapa',
    'Consumer Disputes Redressal Commission, Kadapa',
    'Labour Court, Kadapa',
    'MACT, Kadapa',
    'Chief Judicial Magistrate Court, Kadapa',
  ],
  'rajahmundry': [
    'Principal District & Sessions Court, East Godavari (Rajahmundry)',
    'I Addl. District & Sessions Court, Rajahmundry',
    'Family Court, Rajahmundry',
    'Consumer Disputes Redressal Commission, East Godavari',
    'Labour Court, Rajahmundry',
    'MACT, Rajahmundry',
    'Chief Judicial Magistrate Court, Rajahmundry',
  ],
  'eluru': [
    'Principal District & Sessions Court, West Godavari (Eluru)',
    'Family Court, Eluru',
    'Consumer Disputes Redressal Commission, West Godavari',
    'Labour Court, Eluru',
    'MACT, Eluru',
    'Chief Judicial Magistrate Court, Eluru',
  ],
  'ongole': [
    'Principal District & Sessions Court, Prakasam (Ongole)',
    'Family Court, Ongole',
    'Consumer Disputes Redressal Commission, Prakasam',
    'Labour Court, Ongole',
    'MACT, Ongole',
    'Chief Judicial Magistrate Court, Ongole',
  ],
  'srikakulam': [
    'Principal District & Sessions Court, Srikakulam',
    'Family Court, Srikakulam',
    'Consumer Disputes Redressal Commission, Srikakulam',
    'MACT, Srikakulam',
    'Chief Judicial Magistrate Court, Srikakulam',
  ],
  'vizianagaram': [
    'Principal District & Sessions Court, Vizianagaram',
    'Family Court, Vizianagaram',
    'Consumer Disputes Redressal Commission, Vizianagaram',
    'MACT, Vizianagaram',
    'Chief Judicial Magistrate Court, Vizianagaram',
  ],
  'amaravati': [
    'High Court of Andhra Pradesh, Amaravati',
    'Principal District & Sessions Court, Amaravati',
  ],
  'bhimavaram': [
    'Principal District & Sessions Court, West Godavari (Bhimavaram)',
    'Family Court, Bhimavaram',
    'MACT, Bhimavaram',
    'Chief Judicial Magistrate Court, Bhimavaram',
  ],
  'anantapur': [
    'Principal District & Sessions Court, Anantapur',
    'Family Court, Anantapur',
    'Consumer Disputes Redressal Commission, Anantapur',
    'Labour Court, Anantapur',
    'MACT, Anantapur',
    'Chief Judicial Magistrate Court, Anantapur',
  ],
  // ── TELANGANA ──
  'hyderabad': [
    'High Court of Telangana, Hyderabad',
    'City Civil Court, Hyderabad',
    'Principal District & Sessions Court, Hyderabad',
    'I Addl. District & Sessions Court, Hyderabad',
    'II Addl. District & Sessions Court, Hyderabad',
    'Family Court, Hyderabad',
    'I Addl. Family Court, Hyderabad',
    'Labour Court, Hyderabad',
    'Industrial Tribunal, Hyderabad',
    'Consumer Disputes Redressal Commission, Hyderabad',
    'Motor Accidents Claims Tribunal, Hyderabad',
    'Chief Metropolitan Magistrate Court, Hyderabad',
    'I Addl. Chief Metropolitan Magistrate Court, Hyderabad',
    'Permanent Lok Adalat, Hyderabad',
  ],
  'secunderabad': [
    'Principal District & Sessions Court, Secunderabad',
    'Consumer Disputes Redressal Commission, Secunderabad',
    'Motor Accidents Claims Tribunal, Secunderabad',
  ],
  'warangal': [
    'Principal District & Sessions Court, Warangal',
    'I Addl. District & Sessions Court, Warangal',
    'Family Court, Warangal',
    'Consumer Disputes Redressal Commission, Warangal',
    'Labour Court, Warangal',
    'MACT, Warangal',
    'Chief Judicial Magistrate Court, Warangal',
  ],
  'nizamabad': [
    'Principal District & Sessions Court, Nizamabad',
    'Family Court, Nizamabad',
    'Consumer Disputes Redressal Commission, Nizamabad',
    'MACT, Nizamabad',
    'Chief Judicial Magistrate Court, Nizamabad',
  ],
  'karimnagar': [
    'Principal District & Sessions Court, Karimnagar',
    'Family Court, Karimnagar',
    'Consumer Disputes Redressal Commission, Karimnagar',
    'MACT, Karimnagar',
    'Chief Judicial Magistrate Court, Karimnagar',
  ],
  'khammam': [
    'Principal District & Sessions Court, Khammam',
    'Family Court, Khammam',
    'Consumer Disputes Redressal Commission, Khammam',
    'MACT, Khammam',
    'Chief Judicial Magistrate Court, Khammam',
  ],
  'nalgonda': [
    'Principal District & Sessions Court, Nalgonda',
    'Family Court, Nalgonda',
    'Consumer Disputes Redressal Commission, Nalgonda',
    'MACT, Nalgonda',
    'Chief Judicial Magistrate Court, Nalgonda',
  ],
  'mahbubnagar': [
    'Principal District & Sessions Court, Mahbubnagar',
    'Family Court, Mahbubnagar',
    'Consumer Disputes Redressal Commission, Mahbubnagar',
    'MACT, Mahbubnagar',
    'Chief Judicial Magistrate Court, Mahbubnagar',
  ],
  'rangareddy': [
    'Principal District & Sessions Court, Rangareddy',
    'I Addl. District & Sessions Court, Rangareddy',
    'Family Court, Rangareddy',
    'Consumer Disputes Redressal Commission, Rangareddy',
    'MACT, Rangareddy',
    'Chief Judicial Magistrate Court, Rangareddy',
  ],
  'adilabad': [
    'Principal District & Sessions Court, Adilabad',
    'Family Court, Adilabad',
    'Consumer Disputes Redressal Commission, Adilabad',
    'MACT, Adilabad',
    'Chief Judicial Magistrate Court, Adilabad',
  ],
  // ── KARNATAKA ──
  'bangalore': [
    'High Court of Karnataka, Bangalore',
    'City Civil & Sessions Court, Bangalore',
    'Principal City Civil Court, Bangalore',
    'I Addl. City Civil & Sessions Court, Bangalore',
    'Family Court, Bangalore',
    'Labour Court, Bangalore',
    'Industrial Tribunal, Bangalore',
    'Consumer Disputes Redressal Commission, Bangalore',
    'MACT, Bangalore',
    'Chief Metropolitan Magistrate Court, Bangalore',
    'Permanent Lok Adalat, Bangalore',
  ],
  'bengaluru': [
    'High Court of Karnataka, Bengaluru',
    'City Civil & Sessions Court, Bengaluru',
    'Family Court, Bengaluru',
    'Labour Court, Bengaluru',
    'Consumer Disputes Redressal Commission, Bengaluru',
    'MACT, Bengaluru',
    'Chief Metropolitan Magistrate Court, Bengaluru',
  ],
  'mysore': [
    'Principal District & Sessions Court, Mysore',
    'Family Court, Mysore',
    'Consumer Disputes Redressal Commission, Mysore',
    'Labour Court, Mysore',
    'MACT, Mysore',
    'Chief Judicial Magistrate Court, Mysore',
  ],
  'hubli': [
    'Principal District & Sessions Court, Dharwad (Hubli)',
    'Family Court, Hubli',
    'Consumer Disputes Redressal Commission, Dharwad',
    'Labour Court, Hubli',
    'MACT, Hubli',
    'Chief Judicial Magistrate Court, Hubli',
  ],
  'mangalore': [
    'Principal District & Sessions Court, Dakshina Kannada (Mangalore)',
    'Family Court, Mangalore',
    'Consumer Disputes Redressal Commission, Dakshina Kannada',
    'Labour Court, Mangalore',
    'MACT, Mangalore',
    'Chief Judicial Magistrate Court, Mangalore',
  ],
  'belgaum': [
    'Principal District & Sessions Court, Belagavi',
    'Family Court, Belagavi',
    'Consumer Disputes Redressal Commission, Belagavi',
    'Labour Court, Belagavi',
    'MACT, Belagavi',
    'Chief Judicial Magistrate Court, Belagavi',
  ],
  'belagavi': [
    'Principal District & Sessions Court, Belagavi',
    'Family Court, Belagavi',
    'Consumer Disputes Redressal Commission, Belagavi',
    'Labour Court, Belagavi',
    'MACT, Belagavi',
  ],
  'gulbarga': [
    'Principal District & Sessions Court, Kalaburagi',
    'Family Court, Kalaburagi',
    'Consumer Disputes Redressal Commission, Kalaburagi',
    'MACT, Kalaburagi',
    'Chief Judicial Magistrate Court, Kalaburagi',
  ],
  // ── TAMIL NADU ──
  'chennai': [
    'High Court of Madras, Chennai',
    'City Civil Court, Chennai',
    'Principal District & Sessions Court, Chennai',
    'Family Court, Chennai',
    'I Addl. Family Court, Chennai',
    'Labour Court, Chennai',
    'Industrial Tribunal, Chennai',
    'Consumer Disputes Redressal Commission, Chennai',
    'MACT, Chennai',
    'Chief Metropolitan Magistrate Court, Chennai',
    'Permanent Lok Adalat, Chennai',
  ],
  'coimbatore': [
    'Principal District & Sessions Court, Coimbatore',
    'I Addl. District & Sessions Court, Coimbatore',
    'Family Court, Coimbatore',
    'Consumer Disputes Redressal Commission, Coimbatore',
    'Labour Court, Coimbatore',
    'MACT, Coimbatore',
    'Chief Judicial Magistrate Court, Coimbatore',
  ],
  'madurai': [
    'Madurai Bench of Madras High Court',
    'Principal District & Sessions Court, Madurai',
    'I Addl. District & Sessions Court, Madurai',
    'Family Court, Madurai',
    'Consumer Disputes Redressal Commission, Madurai',
    'Labour Court, Madurai',
    'MACT, Madurai',
    'Chief Judicial Magistrate Court, Madurai',
  ],
  'salem': [
    'Principal District & Sessions Court, Salem',
    'Family Court, Salem',
    'Consumer Disputes Redressal Commission, Salem',
    'Labour Court, Salem',
    'MACT, Salem',
    'Chief Judicial Magistrate Court, Salem',
  ],
  'trichy': [
    'Principal District & Sessions Court, Tiruchirappalli',
    'Family Court, Tiruchirappalli',
    'Consumer Disputes Redressal Commission, Tiruchirappalli',
    'Labour Court, Tiruchirappalli',
    'MACT, Tiruchirappalli',
    'Chief Judicial Magistrate Court, Tiruchirappalli',
  ],
  'tiruchirappalli': [
    'Principal District & Sessions Court, Tiruchirappalli',
    'Family Court, Tiruchirappalli',
    'Consumer Disputes Redressal Commission, Tiruchirappalli',
    'Labour Court, Tiruchirappalli',
    'MACT, Tiruchirappalli',
  ],
  'vellore': [
    'Principal District & Sessions Court, Vellore',
    'Family Court, Vellore',
    'Consumer Disputes Redressal Commission, Vellore',
    'MACT, Vellore',
    'Chief Judicial Magistrate Court, Vellore',
  ],
  'erode': [
    'Principal District & Sessions Court, Erode',
    'Family Court, Erode',
    'Consumer Disputes Redressal Commission, Erode',
    'MACT, Erode',
    'Chief Judicial Magistrate Court, Erode',
  ],
  'tirunelveli': [
    'Principal District & Sessions Court, Tirunelveli',
    'Family Court, Tirunelveli',
    'Consumer Disputes Redressal Commission, Tirunelveli',
    'MACT, Tirunelveli',
    'Chief Judicial Magistrate Court, Tirunelveli',
  ],
  // ── KERALA ──
  'thiruvananthapuram': [
    'Kerala High Court, Thiruvananthapuram',
    'Principal District & Sessions Court, Thiruvananthapuram',
    'I Addl. District & Sessions Court, Thiruvananthapuram',
    'Family Court, Thiruvananthapuram',
    'Consumer Disputes Redressal Commission, Thiruvananthapuram',
    'Labour Court, Thiruvananthapuram',
    'MACT, Thiruvananthapuram',
    'Chief Judicial Magistrate Court, Thiruvananthapuram',
    'Permanent Lok Adalat, Thiruvananthapuram',
  ],
  'kochi': [
    'Principal District & Sessions Court, Ernakulam (Kochi)',
    'I Addl. District & Sessions Court, Kochi',
    'Family Court, Kochi',
    'Consumer Disputes Redressal Commission, Ernakulam',
    'Labour Court, Kochi',
    'MACT, Kochi',
    'Chief Judicial Magistrate Court, Kochi',
  ],
  'ernakulam': [
    'Principal District & Sessions Court, Ernakulam',
    'Family Court, Ernakulam',
    'Consumer Disputes Redressal Commission, Ernakulam',
    'Labour Court, Ernakulam',
    'MACT, Ernakulam',
  ],
  'kozhikode': [
    'Principal District & Sessions Court, Kozhikode',
    'Family Court, Kozhikode',
    'Consumer Disputes Redressal Commission, Kozhikode',
    'Labour Court, Kozhikode',
    'MACT, Kozhikode',
    'Chief Judicial Magistrate Court, Kozhikode',
  ],
  'thrissur': [
    'Principal District & Sessions Court, Thrissur',
    'Family Court, Thrissur',
    'Consumer Disputes Redressal Commission, Thrissur',
    'MACT, Thrissur',
    'Chief Judicial Magistrate Court, Thrissur',
  ],
  'kollam': [
    'Principal District & Sessions Court, Kollam',
    'Family Court, Kollam',
    'Consumer Disputes Redressal Commission, Kollam',
    'MACT, Kollam',
    'Chief Judicial Magistrate Court, Kollam',
  ],
  // ── MAHARASHTRA ──
  'mumbai': [
    'Bombay High Court, Mumbai',
    'City Civil & Sessions Court, Mumbai',
    'Principal City Civil Court, Mumbai',
    'Family Court, Mumbai (Bandra)',
    'Labour Court, Mumbai',
    'Industrial Court, Mumbai',
    'Consumer Disputes Redressal Commission, Mumbai',
    'MACT, Mumbai',
    'Chief Metropolitan Magistrate Court, Mumbai',
    'Debt Recovery Tribunal, Mumbai',
    'Permanent Lok Adalat, Mumbai',
  ],
  'pune': [
    'Principal District & Sessions Court, Pune',
    'I Addl. District & Sessions Court, Pune',
    'Family Court, Pune',
    'Consumer Disputes Redressal Commission, Pune',
    'Labour Court, Pune',
    'MACT, Pune',
    'Chief Judicial Magistrate Court, Pune',
  ],
  'nagpur': [
    'Bombay High Court (Nagpur Bench)',
    'Principal District & Sessions Court, Nagpur',
    'Family Court, Nagpur',
    'Consumer Disputes Redressal Commission, Nagpur',
    'Labour Court, Nagpur',
    'MACT, Nagpur',
    'Chief Judicial Magistrate Court, Nagpur',
  ],
  'nashik': [
    'Principal District & Sessions Court, Nashik',
    'Family Court, Nashik',
    'Consumer Disputes Redressal Commission, Nashik',
    'Labour Court, Nashik',
    'MACT, Nashik',
    'Chief Judicial Magistrate Court, Nashik',
  ],
  'aurangabad': [
    'Bombay High Court (Aurangabad Bench)',
    'Principal District & Sessions Court, Aurangabad',
    'Family Court, Aurangabad',
    'Consumer Disputes Redressal Commission, Aurangabad',
    'Labour Court, Aurangabad',
    'MACT, Aurangabad',
    'Chief Judicial Magistrate Court, Aurangabad',
  ],
  'thane': [
    'Principal District & Sessions Court, Thane',
    'I Addl. District & Sessions Court, Thane',
    'Family Court, Thane',
    'Consumer Disputes Redressal Commission, Thane',
    'Labour Court, Thane',
    'MACT, Thane',
    'Chief Judicial Magistrate Court, Thane',
  ],
  'kolhapur': [
    'Principal District & Sessions Court, Kolhapur',
    'Family Court, Kolhapur',
    'Consumer Disputes Redressal Commission, Kolhapur',
    'MACT, Kolhapur',
    'Chief Judicial Magistrate Court, Kolhapur',
  ],
  // ── DELHI ──
  'delhi': [
    'Delhi High Court',
    'District Court, Saket',
    'District Court, Rohini',
    'District Court, Tis Hazari',
    'District Court, Dwarka',
    'District Court, Karkardooma',
    'District Court, Patiala House',
    'Family Court, Delhi',
    'Labour Court, Delhi',
    'Consumer Disputes Redressal Commission, Delhi',
    'MACT, Delhi',
    'Chief Metropolitan Magistrate Court, Delhi',
    'Debt Recovery Tribunal, Delhi',
    'Permanent Lok Adalat, Delhi',
  ],
  'new delhi': [
    'Delhi High Court',
    'District Court, Saket',
    'District Court, Tis Hazari',
    'District Court, Patiala House',
    'Family Court, New Delhi',
    'Consumer Disputes Redressal Commission, New Delhi',
    'Chief Metropolitan Magistrate Court, New Delhi',
    'Permanent Lok Adalat, New Delhi',
  ],
  // ── GUJARAT ──
  'ahmedabad': [
    'High Court of Gujarat, Ahmedabad',
    'City Civil & Sessions Court, Ahmedabad',
    'Family Court, Ahmedabad',
    'Labour Court, Ahmedabad',
    'Consumer Disputes Redressal Commission, Ahmedabad',
    'MACT, Ahmedabad',
    'Chief Metropolitan Magistrate Court, Ahmedabad',
    'Debt Recovery Tribunal, Ahmedabad',
    'Permanent Lok Adalat, Ahmedabad',
  ],
  'surat': [
    'Principal District & Sessions Court, Surat',
    'Family Court, Surat',
    'Consumer Disputes Redressal Commission, Surat',
    'Labour Court, Surat',
    'MACT, Surat',
    'Chief Judicial Magistrate Court, Surat',
  ],
  'vadodara': [
    'Principal District & Sessions Court, Vadodara',
    'Family Court, Vadodara',
    'Consumer Disputes Redressal Commission, Vadodara',
    'Labour Court, Vadodara',
    'MACT, Vadodara',
    'Chief Judicial Magistrate Court, Vadodara',
  ],
  'rajkot': [
    'Principal District & Sessions Court, Rajkot',
    'Family Court, Rajkot',
    'Consumer Disputes Redressal Commission, Rajkot',
    'Labour Court, Rajkot',
    'MACT, Rajkot',
    'Chief Judicial Magistrate Court, Rajkot',
  ],
  'gandhinagar': [
    'High Court of Gujarat, Gandhinagar',
    'Principal District & Sessions Court, Gandhinagar',
    'Family Court, Gandhinagar',
    'Consumer Disputes Redressal Commission, Gandhinagar',
    'MACT, Gandhinagar',
  ],
  // ── RAJASTHAN ──
  'jaipur': [
    'Rajasthan High Court (Principal Bench), Jaipur',
    'Principal District & Sessions Court, Jaipur',
    'I Addl. District & Sessions Court, Jaipur',
    'Family Court, Jaipur',
    'Consumer Disputes Redressal Commission, Jaipur',
    'Labour Court, Jaipur',
    'MACT, Jaipur',
    'Chief Judicial Magistrate Court, Jaipur',
    'Permanent Lok Adalat, Jaipur',
  ],
  'jodhpur': [
    'Rajasthan High Court (Jodhpur Bench)',
    'Principal District & Sessions Court, Jodhpur',
    'Family Court, Jodhpur',
    'Consumer Disputes Redressal Commission, Jodhpur',
    'Labour Court, Jodhpur',
    'MACT, Jodhpur',
    'Chief Judicial Magistrate Court, Jodhpur',
  ],
  'kota': [
    'Principal District & Sessions Court, Kota',
    'Family Court, Kota',
    'Consumer Disputes Redressal Commission, Kota',
    'Labour Court, Kota',
    'MACT, Kota',
    'Chief Judicial Magistrate Court, Kota',
  ],
  'ajmer': [
    'Principal District & Sessions Court, Ajmer',
    'Family Court, Ajmer',
    'Consumer Disputes Redressal Commission, Ajmer',
    'MACT, Ajmer',
    'Chief Judicial Magistrate Court, Ajmer',
  ],
  // ── UTTAR PRADESH ──
  'lucknow': [
    'Allahabad High Court (Lucknow Bench)',
    'Principal District & Sessions Court, Lucknow',
    'I Addl. District & Sessions Court, Lucknow',
    'Family Court, Lucknow',
    'Consumer Disputes Redressal Commission, Lucknow',
    'Labour Court, Lucknow',
    'MACT, Lucknow',
    'Chief Judicial Magistrate Court, Lucknow',
    'Permanent Lok Adalat, Lucknow',
  ],
  'allahabad': [
    'High Court of Allahabad (Principal Bench), Prayagraj',
    'Principal District & Sessions Court, Prayagraj',
    'Family Court, Prayagraj',
    'Consumer Disputes Redressal Commission, Prayagraj',
    'Labour Court, Prayagraj',
    'MACT, Prayagraj',
    'Chief Judicial Magistrate Court, Prayagraj',
  ],
  'prayagraj': [
    'High Court of Allahabad (Principal Bench), Prayagraj',
    'Principal District & Sessions Court, Prayagraj',
    'Family Court, Prayagraj',
    'Consumer Disputes Redressal Commission, Prayagraj',
    'Labour Court, Prayagraj',
    'MACT, Prayagraj',
    'Chief Judicial Magistrate Court, Prayagraj',
  ],
  'varanasi': [
    'Principal District & Sessions Court, Varanasi',
    'Family Court, Varanasi',
    'Consumer Disputes Redressal Commission, Varanasi',
    'Labour Court, Varanasi',
    'MACT, Varanasi',
    'Chief Judicial Magistrate Court, Varanasi',
  ],
  'agra': [
    'Principal District & Sessions Court, Agra',
    'Family Court, Agra',
    'Consumer Disputes Redressal Commission, Agra',
    'Labour Court, Agra',
    'MACT, Agra',
    'Chief Judicial Magistrate Court, Agra',
  ],
  'kanpur': [
    'Principal District & Sessions Court, Kanpur Nagar',
    'Family Court, Kanpur',
    'Consumer Disputes Redressal Commission, Kanpur',
    'Labour Court, Kanpur',
    'MACT, Kanpur',
    'Chief Judicial Magistrate Court, Kanpur',
  ],
  'meerut': [
    'Principal District & Sessions Court, Meerut',
    'Family Court, Meerut',
    'Consumer Disputes Redressal Commission, Meerut',
    'Labour Court, Meerut',
    'MACT, Meerut',
    'Chief Judicial Magistrate Court, Meerut',
  ],
  'ghaziabad': [
    'Principal District & Sessions Court, Ghaziabad',
    'Family Court, Ghaziabad',
    'Consumer Disputes Redressal Commission, Ghaziabad',
    'MACT, Ghaziabad',
    'Chief Judicial Magistrate Court, Ghaziabad',
  ],
  'noida': [
    'Principal District & Sessions Court, Gautam Buddha Nagar (Noida)',
    'Family Court, Noida',
    'Consumer Disputes Redressal Commission, Gautam Buddha Nagar',
    'MACT, Noida',
    'Chief Judicial Magistrate Court, Noida',
  ],
  // ── WEST BENGAL ──
  'kolkata': [
    'Calcutta High Court, Kolkata',
    'City Sessions Court, Kolkata',
    'City Civil Court, Kolkata',
    'Family Court, Kolkata',
    'Labour Court, Kolkata',
    'Consumer Disputes Redressal Commission, Kolkata',
    'MACT, Kolkata',
    'Chief Metropolitan Magistrate Court, Kolkata',
    'Debt Recovery Tribunal, Kolkata',
    'Permanent Lok Adalat, Kolkata',
  ],
  'howrah': [
    'Principal District & Sessions Court, Howrah',
    'Family Court, Howrah',
    'Consumer Disputes Redressal Commission, Howrah',
    'MACT, Howrah',
    'Chief Judicial Magistrate Court, Howrah',
  ],
  'durgapur': [
    'Principal District & Sessions Court, Burdwan (Durgapur)',
    'Family Court, Durgapur',
    'Consumer Disputes Redressal Commission, Paschim Burdwan',
    'MACT, Durgapur',
    'Chief Judicial Magistrate Court, Durgapur',
  ],
  'siliguri': [
    'Principal District & Sessions Court, Darjeeling (Siliguri)',
    'Family Court, Siliguri',
    'Consumer Disputes Redressal Commission, Darjeeling',
    'MACT, Siliguri',
    'Chief Judicial Magistrate Court, Siliguri',
  ],
  // ── MADHYA PRADESH ──
  'bhopal': [
    'MP High Court (Principal Bench), Jabalpur',
    'Principal District & Sessions Court, Bhopal',
    'I Addl. District & Sessions Court, Bhopal',
    'Family Court, Bhopal',
    'Consumer Disputes Redressal Commission, Bhopal',
    'Labour Court, Bhopal',
    'MACT, Bhopal',
    'Chief Judicial Magistrate Court, Bhopal',
    'Permanent Lok Adalat, Bhopal',
  ],
  'indore': [
    'MP High Court (Indore Bench)',
    'Principal District & Sessions Court, Indore',
    'I Addl. District & Sessions Court, Indore',
    'Family Court, Indore',
    'Consumer Disputes Redressal Commission, Indore',
    'Labour Court, Indore',
    'MACT, Indore',
    'Chief Judicial Magistrate Court, Indore',
  ],
  'gwalior': [
    'MP High Court (Gwalior Bench)',
    'Principal District & Sessions Court, Gwalior',
    'Family Court, Gwalior',
    'Consumer Disputes Redressal Commission, Gwalior',
    'Labour Court, Gwalior',
    'MACT, Gwalior',
    'Chief Judicial Magistrate Court, Gwalior',
  ],
  'jabalpur': [
    'MP High Court (Principal Bench), Jabalpur',
    'Principal District & Sessions Court, Jabalpur',
    'Family Court, Jabalpur',
    'Consumer Disputes Redressal Commission, Jabalpur',
    'Labour Court, Jabalpur',
    'MACT, Jabalpur',
    'Chief Judicial Magistrate Court, Jabalpur',
  ],
  // ── PUNJAB / HARYANA ──
  'chandigarh': [
    'Punjab & Haryana High Court, Chandigarh',
    'District & Sessions Court, Chandigarh',
    'Family Court, Chandigarh',
    'Consumer Disputes Redressal Commission, Chandigarh',
    'Labour Court, Chandigarh',
    'MACT, Chandigarh',
    'Chief Judicial Magistrate Court, Chandigarh',
    'Permanent Lok Adalat, Chandigarh',
  ],
  'amritsar': [
    'Principal District & Sessions Court, Amritsar',
    'Family Court, Amritsar',
    'Consumer Disputes Redressal Commission, Amritsar',
    'Labour Court, Amritsar',
    'MACT, Amritsar',
    'Chief Judicial Magistrate Court, Amritsar',
  ],
  'ludhiana': [
    'Principal District & Sessions Court, Ludhiana',
    'Family Court, Ludhiana',
    'Consumer Disputes Redressal Commission, Ludhiana',
    'Labour Court, Ludhiana',
    'MACT, Ludhiana',
    'Chief Judicial Magistrate Court, Ludhiana',
  ],
  'gurugram': [
    'Principal District & Sessions Court, Gurugram',
    'Family Court, Gurugram',
    'Consumer Disputes Redressal Commission, Gurugram',
    'MACT, Gurugram',
    'Chief Judicial Magistrate Court, Gurugram',
  ],
  'faridabad': [
    'Principal District & Sessions Court, Faridabad',
    'Family Court, Faridabad',
    'Consumer Disputes Redressal Commission, Faridabad',
    'MACT, Faridabad',
    'Chief Judicial Magistrate Court, Faridabad',
  ],
  'ambala': [
    'Principal District & Sessions Court, Ambala',
    'Family Court, Ambala',
    'Consumer Disputes Redressal Commission, Ambala',
    'MACT, Ambala',
    'Chief Judicial Magistrate Court, Ambala',
  ],
  'rohtak': [
    'Principal District & Sessions Court, Rohtak',
    'Family Court, Rohtak',
    'Consumer Disputes Redressal Commission, Rohtak',
    'MACT, Rohtak',
    'Chief Judicial Magistrate Court, Rohtak',
  ],
  // ── BIHAR ──
  'patna': [
    'Patna High Court',
    'Principal District & Sessions Court, Patna',
    'I Addl. District & Sessions Court, Patna',
    'Family Court, Patna',
    'Consumer Disputes Redressal Commission, Patna',
    'Labour Court, Patna',
    'MACT, Patna',
    'Chief Judicial Magistrate Court, Patna',
    'Permanent Lok Adalat, Patna',
  ],
  'gaya': [
    'Principal District & Sessions Court, Gaya',
    'Family Court, Gaya',
    'Consumer Disputes Redressal Commission, Gaya',
    'MACT, Gaya',
    'Chief Judicial Magistrate Court, Gaya',
  ],
  'muzaffarpur': [
    'Principal District & Sessions Court, Muzaffarpur',
    'Family Court, Muzaffarpur',
    'Consumer Disputes Redressal Commission, Muzaffarpur',
    'MACT, Muzaffarpur',
    'Chief Judicial Magistrate Court, Muzaffarpur',
  ],
  // ── ODISHA ──
  'bhubaneswar': [
    'Orissa High Court, Cuttack',
    'Principal District & Sessions Court, Khordha (Bhubaneswar)',
    'Family Court, Bhubaneswar',
    'Consumer Disputes Redressal Commission, Khordha',
    'Labour Court, Bhubaneswar',
    'MACT, Bhubaneswar',
    'Chief Judicial Magistrate Court, Bhubaneswar',
    'Permanent Lok Adalat, Bhubaneswar',
  ],
  'cuttack': [
    'Orissa High Court, Cuttack',
    'Principal District & Sessions Court, Cuttack',
    'Family Court, Cuttack',
    'Consumer Disputes Redressal Commission, Cuttack',
    'Labour Court, Cuttack',
    'MACT, Cuttack',
    'Chief Judicial Magistrate Court, Cuttack',
  ],
  'rourkela': [
    'Principal District & Sessions Court, Sundargarh (Rourkela)',
    'Family Court, Rourkela',
    'Consumer Disputes Redressal Commission, Sundargarh',
    'MACT, Rourkela',
    'Chief Judicial Magistrate Court, Rourkela',
  ],
  // ── ASSAM ──
  'guwahati': [
    'Gauhati High Court, Guwahati',
    'Principal District & Sessions Court, Kamrup Metro (Guwahati)',
    'I Addl. District & Sessions Court, Guwahati',
    'Family Court, Guwahati',
    'Consumer Disputes Redressal Commission, Kamrup',
    'Labour Court, Guwahati',
    'MACT, Guwahati',
    'Chief Judicial Magistrate Court, Guwahati',
    'Permanent Lok Adalat, Guwahati',
  ],
  'dibrugarh': [
    'Principal District & Sessions Court, Dibrugarh',
    'Family Court, Dibrugarh',
    'Consumer Disputes Redressal Commission, Dibrugarh',
    'MACT, Dibrugarh',
    'Chief Judicial Magistrate Court, Dibrugarh',
  ],
  // ── UTTARAKHAND ──
  'dehradun': [
    'Uttarakhand High Court (Nainital Bench)',
    'Principal District & Sessions Court, Dehradun',
    'Family Court, Dehradun',
    'Consumer Disputes Redressal Commission, Dehradun',
    'Labour Court, Dehradun',
    'MACT, Dehradun',
    'Chief Judicial Magistrate Court, Dehradun',
    'Permanent Lok Adalat, Dehradun',
  ],
  'nainital': [
    'Uttarakhand High Court, Nainital',
    'Principal District & Sessions Court, Nainital',
    'Family Court, Nainital',
    'Consumer Disputes Redressal Commission, Nainital',
    'Chief Judicial Magistrate Court, Nainital',
  ],
  // ── JHARKHAND ──
  'ranchi': [
    'Jharkhand High Court, Ranchi',
    'Principal District & Sessions Court, Ranchi',
    'I Addl. District & Sessions Court, Ranchi',
    'Family Court, Ranchi',
    'Consumer Disputes Redressal Commission, Ranchi',
    'Labour Court, Ranchi',
    'MACT, Ranchi',
    'Chief Judicial Magistrate Court, Ranchi',
    'Permanent Lok Adalat, Ranchi',
  ],
  'dhanbad': [
    'Principal District & Sessions Court, Dhanbad',
    'Family Court, Dhanbad',
    'Consumer Disputes Redressal Commission, Dhanbad',
    'Labour Court, Dhanbad',
    'MACT, Dhanbad',
    'Chief Judicial Magistrate Court, Dhanbad',
  ],
  // ── CHHATTISGARH ──
  'raipur': [
    'Chhattisgarh High Court (Bilaspur)',
    'Principal District & Sessions Court, Raipur',
    'I Addl. District & Sessions Court, Raipur',
    'Family Court, Raipur',
    'Consumer Disputes Redressal Commission, Raipur',
    'Labour Court, Raipur',
    'MACT, Raipur',
    'Chief Judicial Magistrate Court, Raipur',
    'Permanent Lok Adalat, Raipur',
  ],
  'bilaspur': [
    'Chhattisgarh High Court, Bilaspur',
    'Principal District & Sessions Court, Bilaspur',
    'Family Court, Bilaspur',
    'Consumer Disputes Redressal Commission, Bilaspur',
    'Labour Court, Bilaspur',
    'MACT, Bilaspur',
    'Chief Judicial Magistrate Court, Bilaspur',
  ],
  // ── HIMACHAL PRADESH ──
  'shimla': [
    'Himachal Pradesh High Court, Shimla',
    'Principal District & Sessions Court, Shimla',
    'Family Court, Shimla',
    'Consumer Disputes Redressal Commission, Shimla',
    'Labour Court, Shimla',
    'MACT, Shimla',
    'Chief Judicial Magistrate Court, Shimla',
    'Permanent Lok Adalat, Shimla',
  ],
  // ── GOA ──
  'panaji': [
    'Bombay High Court (Goa Bench), Panaji',
    'Principal District & Sessions Court, North Goa (Panaji)',
    'Family Court, Panaji',
    'Consumer Disputes Redressal Commission, North Goa',
    'Labour Court, Panaji',
    'MACT, Panaji',
    'Chief Judicial Magistrate Court, Panaji',
  ],
  'vasco': [
    'Principal District & Sessions Court, South Goa (Margao)',
    'Consumer Disputes Redressal Commission, South Goa',
    'MACT, Margao',
    'Chief Judicial Magistrate Court, Margao',
  ],
  // ── PUDUCHERRY ──
  'puducherry': [
    'District Court, Puducherry',
    'Family Court, Puducherry',
    'Consumer Disputes Redressal Commission, Puducherry',
    'Labour Court, Puducherry',
    'MACT, Puducherry',
    'Chief Judicial Magistrate Court, Puducherry',
  ],
  'pondicherry': [
    'District Court, Puducherry',
    'Family Court, Puducherry',
    'Consumer Disputes Redressal Commission, Puducherry',
    'Labour Court, Puducherry',
    'MACT, Puducherry',
  ],
}

export function getCourtsForCity(input) {
  if (!input || input.trim().length < 2) return []
  const search = input.toLowerCase().trim()
  const results = []
  for (const [city, courts] of Object.entries(COURTS_BY_CITY)) {
    if (city.includes(search) || search.includes(city)) {
      results.push(...courts)
    }
  }
  // Remove duplicates
  return [...new Set(results)]
}

export const ALL_CITY_NAMES = Object.keys(COURTS_BY_CITY)
  .map(c => c.charAt(0).toUpperCase() + c.slice(1))
  .sort()
